### ISSUE TITLE
Wrong dynamic library for gcc?

### ISSUE THREAD

**Issue by lygamac** [godot-rust/godot-rust-template#39]
I used the godot-rust template and when running `make run`, and the following error came out:
```
ERROR: Can't open dynamic library: D:/rust/my-awesome-game/godot/../lib/x86_64-pc-windows-msvc/my_awesome_game.dll, error: Error 126: The specified module could not be found.
```
I used gcc for building, so there's nothing under `x86_64-pc-windows-msvc`, and the `my_awesome_game.dll` is under `x86_64-pc-windows-gnu` instead.

---

In addition,
```
run:
	make build-x86_64-pc-windows-gnu-debug
	godot --path godot/ -d
	# make build-x86_64-pc-windows-msvc-debug
```
I moved the commented part down, because when it (or the gcc, I tried both) is above `godot --path godot/ -d` there's also a error despite being commented:
```
mingw32-make[1]: Leaving directory 'D:/rust/my-awesome-game'
# make build-x86_64-pc-windows-msvc-debug
process_begin: CreateProcess(NULL, # make build-x86_64-pc-windows-msvc-debug, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make: *** [Makefile:249: run] Error 2
```

**Comment by toasteater** [comment]
Firstly, you need to use the same ABI as the Godot executable you're planning to use the binary with. The official release is apparently compiled with MSVC IIRC, so unless you compile the editor and an export template yourself, any binaries you compiled targeting `-gnu` won't work.

Secondly, this appears to be an issue with the template, instead of the library proper. As such, I have moved it to the template repo.

@macalimlim Could you take a look and see whether this is a user error or something wrong with the template?

**Comment by lygamac** [comment]
Does the binary compiled by MSVC work when it's under a linux environment with gcc, for example?

Or should I keep a binary for each platform independently?

**Comment by Bromeon** [comment]
Binaries compiled by MSVC run on Windows, you won't even be able to execute them on Linux.

Yes, for any native language you'll need to recompile binaries for different platforms. Luckily, with Rust this is relatively easy.
In the Godot editor, the `GDNativeLibrary` resource (`.gdnlib` file) gives you a table, where you can enter the dynamic libraries of different platforms.

See [here](https://docs.godotengine.org/en/stable/tutorials/plugins/gdnative/gdnative-c-example.html#creating-the-gdnativelibrary-gdnlib-file) for an example. The page is about C, but many of the things apply to GDNative in general.

**Comment by macalimlim** [comment]
Hi @lygamac , thankyou for filing this issue. Have you also commented the `msvc` and uncommented the `gnu` parts in the gdnlib file?

**Comment by lygamac** [comment]
> Have you also commented the `msvc` and uncommented the `gnu` parts in the gdnlib file?

Just tried, it still looks for `msvc` instead of `gnu`.

About the makefile, as the makefile syntax guide states:
> Comments within a recipe are passed to the shell, just as with any other recipe text. The shell decides how to interpret it: whether or not this is a comment is up to the shell. 

In my case (powershell), the behavior is the following:
```
run:
# test                                                 <-- this is treated as comment
	# test                                         <-- this is NOT treated as comment
	make build-x86_64-pc-windows-msvc-debug
	godot --path godot/ -d
# make build-x86_64-pc-windows-gnu-debug               <-- this is treated as comment
	# make build-x86_64-pc-windows-gnu-debug       <-- this is NOT treated as comment
```

**Comment by macalimlim** [comment]
yeah seems like the Makefile's comments work differently in Windows. I will add this on the wiki in case another user gets same error.

**Comment by macalimlim** [comment]
@lygamac I already document it [here](https://github.com/godot-rust/godot-rust-template/wiki#for-windows). Is it working now if you just remove the line?

**Comment by lygamac** [comment]
@macalimlim yes, removing the line or the indent before `#` makes powershell to treat it as a comment.

**Comment by macalimlim** [comment]
@lygamac  Have you also tried using [ftw](https://github.com/macalimlim/ftw)? It also uses the template, but does not use the Makefile to run, build and export stuff.

**Comment by macalimlim** [comment]
If there is nothing else we can help you with, I will be closing this issue. Again thank you for pointing this out 👍🏾

**Comment by lygamac** [comment]
Yup, thanks
